[package]
name = "easy_config"
version = "0.0.1"
authors = ["liming <liming@admaster.com.cn>"]

[dependencies]
rustc-serialize = "0.3.16"
easy_util = {git = "https://limitee:20131988lm@github.com/limitee/easy_util.git"}
lazy_static = "0.1.15"
log = "0.3.5"
